spring.application.name=Fedisea

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fedisea}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}